_target_: src.models.rcnn_module.RCNNModule

embedding_size: 16
hidden_state_size: 32
kernel_size: 3
n_cells_hor: ${n_cells_hor}
n_cells_ver: ${n_cells_ver}
history_length: ${history_length}
batch_size: ${batch_size}
lr: 0.003
weight_decay: 0
